const GameData = [
  {
    id: 1,
    img: "Images/slide1.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 2,
    img: "Images/slide2.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 3,
    img: "Images/slide3.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 4,
    img: "Images/thumb1.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 5,
    img: "Images/thumb2.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 6,
    img: "Images/thumb3.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 7,
    img: "Images/thumb4.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 8,
    img: "Images/thumb5.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 9,
    img: "Images/thumb6.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
];

export default GameData;
