const MindGameData = [
  {
    id: 1,
    img: "Images/mind4.jpg",
    title: "IronMan",
    geners: "Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 2,
    img: "Images/mind5.jpg",
    title: "Build City",
    geners: "Mind, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 3,
    img: "Images/mind6.jpg",
    title: "Futurastic City",
    geners: "Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 4,
    img: "Images/thumb1.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 5,
    img: "Images/thumb2.jpg",
    title: "War",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 6,
    img: "Images/thumb3.jpg",
    title: "Martial Combat",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 7,
    img: "Images/mind3.jpg",
    title: "Word Game",
    geners: "Mind Game",
    rating: "4.5",
    price: "free",
  },
  {
    id: 8,
    img: "Images/mindg1.jpg",
    title: "Traditional Chess",
    geners: "Mind Game",
    rating: "4.5",
    price: "free",
  },
  {
    id: 9,
    img: "Images/mind2.jpg",
    title: "Solve Puzzle",
    geners: "Mind Game",
    rating: "4.5",
    price: "free",
  },
];

export default MindGameData;
