const TredingGames = [
  {
    id: 1,
    img: "Images/slide1.jpg",
    title: "PUBG",
    geners: "Action, Adventure",
    rating: "4.5",
    link: "/firstgame",
    price: "free",
  },
  {
    id: 2,
    img: "Images/slide2.jpg",
    title: "Recore",
    geners: "Action, Adventure",
    link: "/secondgame",
    rating: "4.5",
    price: "free",
  },
  {
    id: 3,
    img: "Images/slide3.jpg",
    title: "Race",
    geners: "Race, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 4,
    img: "Images/thumb1.jpg",
    title: "Martial Combat",
    geners: "Action",
    rating: "4.5",
    price: "free",
  },
  {
    id: 5,
    img: "Images/thumb2.jpg",
    title: "War",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 6,
    img: "Images/thumb3.jpg",
    title: "Martial Combat 5",
    geners: "Action",
    rating: "4.5",
    price: "free",
  },
  {
    id: 7,
    img: "Images/thumb4.jpg",
    title: "Black Knight",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 8,
    img: "Images/thumb5.jpg",
    title: "Uncharted 4",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
  {
    id: 9,
    img: "Images/thumb6.jpg",
    title: "Uncharted 3",
    geners: "Action, Adventure",
    rating: "4.5",
    price: "free",
  },
];

export default TredingGames;
